FROM php:8.2-fpm-alpine3.18

RUN docker-php-ext-install pdo_mysql && docker-php-ext-enable pdo_mysql

CMD ["php-fpm"]

#install some useful tools
#start with composer
RUN wget -q https://getcomposer.org/download/2.5.8/composer.phar -O /usr/local/bin/composer && \
    chmod a+x /usr/local/bin/composer

#install xdebug
RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS git && \
    apk add --no-cache libpng-dev icu-dev libzip-dev && \
    apk add --update linux-headers && \
    pecl channel-update pecl.php.net && pecl install xdebug && \
    docker-php-ext-enable xdebug

WORKDIR /app
