FROM nginx:1.25-alpine-slim

RUN echo $'server { \n\
              listen       80 default; \n\
              server_name  localhost; \n\
              root         /app/public; \n\

              access_log /dev/stdout; \n\
              error_log  /dev/stderr; \n\
              client_max_body_size 100M; \n\

              location ~ ^/(auth|user-profile)/\.well-known/cognito\.pem$ { \n\
                  fastcgi_pass "php:9000"; \n\
                  include fastcgi_params; \n\
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; \n\
                  fastcgi_param DOCUMENT_ROOT $document_root; \n\
              } \n\

              location / { \n\
                  try_files $uri $uri/ @php; \n\
              } \n\

              location @php { \n\
                  fastcgi_read_timeout 95s; \n\
                  fastcgi_pass "php:9000"; \n\
                  fastcgi_split_path_info ^(.+\.php)(/.*)$; \n\
                  include fastcgi_params; \n\
                  fastcgi_param SCRIPT_FILENAME $document_root/index.php; \n\
                  fastcgi_param DOCUMENT_ROOT $document_root; \n\
                  internal; \n\
              } \n\

              location ~ \.php$ { \n\
                  return 404; \n\
              } \n\

              location ~ /\. { \n\
                  deny all; \n\
              } \n\
          } \n\
' > /etc/nginx/conf.d/default.conf

EXPOSE 80
