services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\LogAnalyticsService\Application\RetrieveAggregatedCount\RetrieveLogsAggregatedCountService: ~
  App\LogAnalyticsService\Application\TruncateServiceLog\TruncateServiceLogService: ~
  App\LogAnalyticsService\Application\StoreServiceLog\StoreLogService: ~
