services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\LogAnalyticsService\Infrastructure\Repository\DoctrineDbalServiceLogRepository: ~
  App\LogAnalyticsService\Infrastructure\ServiceLogImporter: ~

  App\LogAnalyticsService\Infrastructure\Extractor\LogParser: ~

when@test:
  services:
    _defaults:
      autowire: true
      autoconfigure: true

    App\Tests\Mock\Infrastructure\Repository\ServiceLogRepositorySpy: ~

when@behat:
  services:
    _defaults:
      autowire: true
      autoconfigure: true

    App\Tests\Behat\Context\FeatureContext: ~
